draw_sprite_ext(argument0,argument1,argument2,argument3,argument4,argument5,argument6,argument7,argument8)
draw_set_blend_mode(bm_add)
d3d_set_fog(1,c_blue,0,0)
draw_sprite_ext(argument0,argument1,argument2,argument3,argument4,argument5,argument6,argument7,.8*argument8)
d3d_set_fog(1,c_aqua,0,0)
draw_sprite_ext(argument0,argument1,argument2,argument3,argument4,argument5,argument6,argument7,.4*argument8)
draw_set_blend_mode(bm_normal)
d3d_set_fog(0,0,0,0) 
